# Generated by Django 3.2.6 on 2021-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='atype',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
