# Generated by Django 3.2.6 on 2021-09-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0002_signup_atype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('modelno', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('screen', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=30)),
                ('graphics', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='atype',
        ),
    ]
