# Generated by Django 3.2.6 on 2021-09-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0003_auto_20210902_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='atype',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
