# Generated by Django 3.2.6 on 2021-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0006_alter_companies_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='id',
        ),
        migrations.AlterField(
            model_name='companies',
            name='modelno',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
