# Generated by Django 3.2.6 on 2021-09-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0007_auto_20210902_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companies',
            name='ioports',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companies',
            name='memory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companies',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companies',
            name='graphics',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companies',
            name='modelno',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companies',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companies',
            name='processor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companies',
            name='screen',
            field=models.CharField(max_length=100),
        ),
    ]
