# Generated by Django 3.2.6 on 2021-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0008_auto_20210903_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='category',
            field=models.IntegerField(choices=[(0, 'Gaming'), (1, 'Business'), (2, 'Professional'), (3, 'Student')], default=2),
        ),
    ]
