# Generated by Django 3.2.6 on 2021-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0009_alter_companies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='modelno',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
