# Generated by Django 3.2.6 on 2021-09-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0010_alter_companies_modelno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='modelno',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
