# Generated by Django 3.2.6 on 2021-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0011_alter_companies_modelno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='category',
            field=models.CharField(choices=[(0, 'Gaming'), (1, 'Business'), (2, 'Professional'), (3, 'Student')], max_length=20),
        ),
    ]
