# Generated by Django 3.2.6 on 2021-09-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0012_alter_companies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Business', 'Business'), ('Professional', 'Professional'), ('Student', 'Student')], max_length=20),
        ),
    ]
