# Generated by Django 3.2.6 on 2021-09-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0013_alter_companies_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
