# Generated by Django 3.2.6 on 2021-09-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0016_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcountDetails',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('phoneno', models.IntegerField()),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profileimages')),
                ('dateofbirth', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
